name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - run: npm install -g aws-cdk@1.80.0
      - run: npx @jakepartusch/notlify --domain=homebrewer.dev --subDomain=test --api=./api/lambda.ts --ui=./ui/build
