name: Serverless UI Build & Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: cd infrastructure && npm ci
      - run: npm install -g aws-cdk
      - run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: npm run deploy
      - name: Add PR Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const manifest = require(`${process.env.GITHUB_WORKSPACE}/infrastructure/cdk.out/manifest.json`);
            const stackName = Object.keys(manifest.artifacts).find((key) =>
              key.startsWith("ServerlessUI")
            );
            const template = require(`${process.env.GITHUB_WORKSPACE}/infrastructure/cdk.out/${stackName}.template.json`);
            const baseUrlKey = Object.keys(template.Outputs).find((key) =>
              key.startsWith("ServerlessUIBaseUrl")
            );
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Your deploy preview is ready: ${template.Outputs[baseUrlKey].Value}`,
            });
